theme:            minimal-mistakes
title:            MyPage
description:      "Hello"
#logo:             wmap_univ.png
#disqus_shortname: thakur_blog
# Assign a default image for your site's header and footer
#default_bg:       default_bg3.jpg
search:           true
share:            true
# Read Time is a calculator to provide post read-time based on word count. Usage is recommended.
readtime:         true
# Specify the average Words per minute. If not defined, 180 will be used
wpm:				      200
# Turn on or off the fin animations in the header and footer
triangleheader:		true
animated_fins:	  true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
baseurl: "/"
url:       		   "http://SoumyadeepThakur.github.io"

# Owner/author information
owner:
  name:           Soumyadeep Thakur
#  avatar:         prof_pic.jpg
  email:          soumyadeep.thakur@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         SoumyadeepThakur
  stackexchange:  
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
#google_analytics:   UA-80845562-1
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
#  - title: About
#    url: /arkya-chatterjee
#  - title: Contact
#    url: /contact
#  - title: My Reading List
#    url: /bookworm

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

gems: [jekyll-paginate]


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

